[HYPI-532] addition of permission documentation
hypi-universe/docs-legacy pull request #4
Opened 2020-08-03 10:00 UTC by evioncane

2020-08-03 12:20 UTC, zcourts requested changes
Make sure all the request data are valid JSON - that https://jsoneditoronline.org/ can parse it successfully.

2020-08-03 12:20 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation.md
> +      type AggregatedPolicy implements Policy @indices(sets: [
Remove the @indices directive. It distracts and probably won't be useful for most readers

2020-08-03 12:20 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
> +For the examples below we will need some data. Use add these entries to be able to get the results shown in the example.
`Use add these entries` -  did you mean just `Add these entries`

2020-08-03 12:20 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
> +Allows protecting a specific resource by ID. The owner of the resource can give permission for other users to access the resource and also can give permission for other users to modify permissions of
It's also worth stating that the permission relation objects are all included in the core app. So `ResourceBasedPermission`, the other permission types and all policies. So no schema needs to be shown below

2020-08-03 12:20 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
> +              name            : 'rbp2',
Use double quotes `"` so that the object is valid JSON. Right now this is still groovy, the structure is the same but a user won't be able to copy and paste it into the editor for use without modifying

2020-08-03 12:20 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
> +                        [hypi: [id: accId1]]
`accId1` is a variable from Groovy, use a string in the examples so it's valid JSON as mentioned above e.g. `"accId1"` and the mention that `accId1` is the ID of the account that is being given access.

2020-08-09 08:40 UTC, evioncane commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
> +Allows protecting a specific resource by ID. The owner of the resource can give permission for other users to access the resource and also can give permission for other users to modify permissions of
Do you mean I should leave only the id in the upsert function?

2020-08-09 11:35 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
> +Allows protecting a specific resource by ID. The owner of the resource can give permission for other users to access the resource and also can give permission for other users to modify permissions of
Ah, no. I mean, in the other documentation pages we start by showing the definition of all the types used in the schema. I'm just saying we could mention here that we have done this because the types are defined in the core app.

2020-08-09 11:36 UTC, zcourts commented on content/products/00-axiom/10-permission-and-authorisation/00-resource-based-permission.md
>                        hypi    : [id: 'r1'],
You still have single quotes. Can you go through all the examples and make sure single quotes are removed from all of them and the object is valid JSON.

2020-08-10 04:11 UTC, merged